---
title: "CITES trade networks in DiagrammeR"
author: "Tamora James"
date: "07/11/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(DiagrammeR)
library(RColorBrewer)
pal <- brewer.pal(n = 8, "Dark2")
```

CITES trade statistics are derived from the [CITES Trade Database, UNEP World Conservation Monitoring Centre, Cambridge, UK](https://trade.cites.org/en/cites_trade/).

```{r data-import}
citesData <- read.csv("data/comptab_Amazona_barbadensis_1975-2017.csv",
                      stringsAsFactors = FALSE)
desc <- "Trade in Amazona barbadensis 1975-2017"
```

```{r node-setup}
## Get list of unique node names for all trade roles
node_names <- citesData %>% 
  select(Importer, Exporter, Origin) %>% 
  unlist(use.names = FALSE) %>% 
  unique()
node_names <- node_names[node_names != ""]

## Create node data frame for trade nodes
nodes <- create_node_df(
    n = length(node_names),
    type = node_names,
    label = node_names,
    ## Additional attributes: trade roles
    exporter = node_names %in% citesData$Exporter,
    importer = node_names %in% citesData$Importer,
    origin = node_names %in% citesData$Origin
)
head(nodes)
```

```{r edge-setup}
## Create edges for each trade relationship
edges_e <-
    create_edge_df(
        from = nodes$id[match(citesData$Exporter, nodes$type)],
        to = nodes$id[match(citesData$Importer, nodes$type)],
        rel = "export",
        data = citesData$Exporter.reported.quantity,
        source = citesData$Source,
        penwidth = ifelse(is.na(citesData$Exporter.reported.quantity), 1,
                          log(citesData$Exporter.reported.quantity+1)),
        color = pal[1]
    )

edges_i <-
    create_edge_df(
        from = nodes$id[match(citesData$Exporter, nodes$type)],
        to = nodes$id[match(citesData$Importer, nodes$type)],
        rel = "import",
        data = citesData$Importer.reported.quantity,
        source = citesData$Source,
        penwidth = ifelse(is.na(citesData$Importer.reported.quantity), 1,
                          log(citesData$Importer.reported.quantity+1)),
        color = pal[2]
    )

edges <- combine_edfs(edges_e,
                      edges_i)

head(edges)
```
```{r create-graph-1}
cites_graph <- create_graph(nodes_df = nodes,
                            edges_df = edges
                            )

## We get a crazy graph because there are many edges between some node pairs.
render_graph(cites_graph,
             title = desc,
             layout = "neato"
             )
```

```{r}
## Filter to only reported imports
cites_graph %>%
    select_edges(conditions = rel == "import") %>%
    render_graph()

```

```{r}
## To make the diagram more manageable, combine edges for trade between same countries (taking the maximum reported quantity)
exportSummary <- citesData %>%
  group_by(Exporter, Importer) %>%
  summarise(quantity = sum(max(Importer.reported.quantity, Exporter.reported.quantity, na.rm = TRUE)))

## Create edges for trade summary
## (N.B. It would be fun to calculate the distance between countries and set the edge lengths accordingly but for the moment I'll leave it to select default values.)
edges_e2 <-
  create_edge_df(
    from = nodes$id[match(exportSummary$Exporter, nodes$type)],
    to = nodes$id[match(exportSummary$Importer, nodes$type)],
    rel = "export",
    data = exportSummary$quantity,
    penwidth = log(exportSummary$quantity+1)
    )

cites_graph2 <- create_graph(nodes_df = nodes,
                             edges_df = edges_e2
)

render_graph(cites_graph2,
             title = desc,
             layout = "nicely"  # options are: nicely, circle, tree, kk, and fr
)
```

